T32892 update search urls
endlessm/kolibri-installer-gnome pull request #5
Opened 2022-01-12 02:47 UTC by dylanmccall

https://phabricator.endlessm.com/T32892

2022-01-19 12:17 UTC, danigm requested changes
Looks almost good to me. The only real problem that I see here is the test running by default, because at least in my builds with `flatpak-builder` that didn't work, so maybe we can disable by default with `"run-tests" : false` in the flatpak manifest.

2022-01-19 12:17 UTC, danigm commented on tests/kolibri_gnome_tests/meson.build
> +test(
This test is running by default for me when I try to build the app with `flatpak-builder`:

```
(python3 -m unittest:8): Gtk-ERROR **: 12:20:42.054: Can't create a GtkStyleContext without a display connection
```

It looks like it needs a display connection, I don't know if this will affect the flathub build. At least with gnome-builder is building the app correctly.

2022-01-19 20:36 UTC, dylanmccall commented on tests/kolibri_gnome_tests/meson.build
> +test(
Good spotting! I added `"test-args" : [ "--socket=fallback-x11", "--socket=wayland" ]` here to solve this - I think flathub runs builds inside xvfb to help with this kind of stuff :)

2022-01-20 10:38 UTC, danigm commented on tests/kolibri_gnome_tests/meson.build
> +test(
Nice, it's working correctly now

2022-01-20 10:38 UTC, danigm approved these changes
Looks good to me

2022-01-22 01:40 UTC, merged